### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by DedsecKnight** [DedsecKnight/the-sat-guys-frontend#11]
### 1. Do Now: 
- [x] ~~Add onClick trigger to Action buttons on step 5 of Generate~~
- [x] ~~Refactor JSON object for `generateConfig`~~
- [x] ~~Implement authentication~~
- [x] ~~Change all occurrences of `normal` to `medium`~~
- [x] ~~Add counter for Difficulty Distribution page~~
- [x] ~~Add sticky top for Notification View~~
- [x] ~~Modify `topicDist` to match with backend specification~~
- [x] ~~Add author ID to `questionConfig`~~

### 2. Do later: 
- [ ] Add loading while rendering pages
- [ ] Fix logo scale in NavBar
- [ ] Implement mobile view
